# Generated by Django 4.1.3 on 2022-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic_gaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price_gaz', models.FileField(upload_to='price/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
