# Generated by Django 4.1.3 on 2022-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_OT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('video_ot', models.FileField(upload_to='video//', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Видео ОТ',
                'verbose_name_plural': 'Видео ОТ',
            },
        ),
        migrations.AlterModelOptions(
            name='traffic_gaz',
            options={'verbose_name': 'Тариф на газ', 'verbose_name_plural': 'Тарифы на газ'},
        ),
    ]
