# Generated by Django 4.1.3 on 2023-03-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_ot_alter_traffic_gaz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure_and_time_limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('video_ot', models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Порядок и сроки обжалования принятых административных решений',
                'verbose_name_plural': 'Порядок и сроки обжалования принятых административных решений',
            },
        ),
    ]
