# Generated by Django 4.1.3 on 2023-03-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_procedure_and_time_limits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure_and_time_limits',
            old_name='video_ot',
            new_name='Procedure_and_time_limits',
        ),
    ]
