# Generated by Django 4.1.3 on 2023-03-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_video_ot_procedure_and_time_limits_procedure_and_time_limits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure_and_time_limits',
            old_name='Procedure_and_time_limits',
            new_name='file',
        ),
    ]
