# Generated by Django 4.1.3 on 2023-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lists_of_administrative_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='leadership_GPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство ГПО Белтопгаз',
                'verbose_name_plural': 'Руководство ГПО Белтопгаз',
            },
        ),
        migrations.CreateModel(
            name='leadership_Minenergo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Минэнерго',
                'verbose_name_plural': 'Руководство Минэнерго',
            },
        ),
        migrations.CreateModel(
            name='leadership_Oblgas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Витебскоблгаз',
                'verbose_name_plural': 'Руководство Витебскоблгаз',
            },
        ),
        migrations.CreateModel(
            name='leadership_Polotsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Полоцкгаз',
                'verbose_name_plural': 'Руководство Полоцкгаз',
            },
        ),
    ]
