# Generated by Django 4.1.3 on 2023-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_leadership_gpo_leadership_minenergo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_of_operation_and_schedule_of_reception_of_citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Mode_of_operation_and_schedule_of_reception_of_citizens/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Режим работы и график приема граждан',
                'verbose_name_plural': 'Режим работы и график приема граждан',
            },
        ),
        migrations.AlterField(
            model_name='leadership_gpo',
            name='file',
            field=models.FileField(upload_to='Leadership/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='leadership_minenergo',
            name='file',
            field=models.FileField(upload_to='Leadership/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='leadership_oblgas',
            name='file',
            field=models.FileField(upload_to='Leadership/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='leadership_polotsk',
            name='file',
            field=models.FileField(upload_to='Leadership/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lists_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Lists_of_administrative_procedures/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='rights_and_obligations_of_citizens_in_the_implementation_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Rights_and_obligations_of_citizens_in_the_implementation_of_administrative_procedures/', verbose_name='Файл'),
        ),
    ]
