# Generated by Django 4.1.3 on 2023-04-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_resolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='BRSM/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'БРСМ ',
                'verbose_name_plural': 'БРСМ ',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Laws/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Законы ',
                'verbose_name_plural': 'Законы ',
            },
        ),
        migrations.CreateModel(
            name='Ordinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Ordinances/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Указы ',
                'verbose_name_plural': 'Указы ',
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Others/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Others ',
                'verbose_name_plural': 'Others ',
            },
        ),
    ]
