# Generated by Django 4.1.3 on 2023-04-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_brsm_laws_ordinances_others'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='others',
            options={'verbose_name': 'Другое ', 'verbose_name_plural': 'Другое '},
        ),
    ]
