# Generated by Django 4.1.3 on 2023-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_others_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BRSM',
        ),
        migrations.DeleteModel(
            name='Decrees',
        ),
        migrations.DeleteModel(
            name='Directives',
        ),
        migrations.DeleteModel(
            name='Document_forms',
        ),
        migrations.DeleteModel(
            name='Laws',
        ),
        migrations.DeleteModel(
            name='leadership_GPO',
        ),
        migrations.DeleteModel(
            name='leadership_Minenergo',
        ),
        migrations.DeleteModel(
            name='leadership_Oblgas',
        ),
        migrations.DeleteModel(
            name='leadership_Polotsk',
        ),
        migrations.DeleteModel(
            name='Mode_of_operation_and_schedule_of_reception_of_citizens',
        ),
        migrations.DeleteModel(
            name='Ordinances',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='Resolutions',
        ),
        migrations.AlterField(
            model_name='lists_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='rights_and_obligations_of_citizens_in_the_implementation_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Procedure_and_time_limits/', verbose_name='Файл'),
        ),
    ]
