# Generated by Django 4.1.3 on 2023-05-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_brsm_delete_decrees_delete_directives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='BRSM/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'БРСМ',
                'verbose_name_plural': 'БРСМ',
            },
        ),
        migrations.CreateModel(
            name='leadership_GPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='leadership_GPO/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство ГПО',
                'verbose_name_plural': 'Руководство ГПО',
            },
        ),
        migrations.CreateModel(
            name='leadership_Minenergo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='leadership_Minenergo/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Минэнерго',
                'verbose_name_plural': 'Руководство Минэнерго',
            },
        ),
        migrations.CreateModel(
            name='leadership_Oblgas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='leadership_Oblgas/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Облгаз',
                'verbose_name_plural': 'Руководство Облгаз',
            },
        ),
        migrations.CreateModel(
            name='leadership_Polotsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='leadership_Polotsk/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Руководство Полоцкгаз',
                'verbose_name_plural': 'Руководство Полоцкгаз',
            },
        ),
        migrations.AlterField(
            model_name='lists_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Lists_of_administrative_procedures/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='rights_and_obligations_of_citizens_in_the_implementation_of_administrative_procedures',
            name='file',
            field=models.FileField(upload_to='Rights_and_obligations_of_citizens_in_the_implementation_of_administrative_procedures/', verbose_name='Файл'),
        ),
    ]
