# Generated by Django 4.1.3 on 2023-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_brsm_leadership_gpo_leadership_minenergo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_of_operation_and_schedule_of_reception_of_citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Mode_of_operation_and_schedule_of_reception_of_citizens/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Режим работы и график приема граждан',
                'verbose_name_plural': 'Режим работы и график приема граждан',
            },
        ),
    ]
