# Generated by Django 4.1.3 on 2023-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mode_of_operation_and_schedule_of_reception_of_citizens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='Document_forms/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Формы(бланки) документов',
                'verbose_name_plural': 'Формы(бланки) документов',
            },
        ),
    ]
