# Generated by Django 4.1.3 on 2023-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_decrees_directives_laws_ordinances_others_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('video_ot', models.FileField(upload_to='video/', verbose_name='Файл')),
                ('times', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AlterModelOptions(
            name='video_ot',
            options={'verbose_name': 'Видеоинструктажи', 'verbose_name_plural': 'Видеоинструктажи'},
        ),
    ]
